<script type="application/ld+json"
    class="yoast-schema-graph">
    {
      "@context":"https://schema.org",
      "@graph":
      [
        {
          "@type":"CollectionPage",
          "@id":"https://moviesmod.com.pl/",
          "url":"https://moviesmod.com.pl/",
          "name":"MoviesMod &#8211; MoviesFlix | TheMoviesverse | TheMoviesMod | TopMovies | ModList.in",
          "isPartOf":{
            "@id":"https://moviesmod.com.pl/#website"
          },
          "about":{
            "@id":"https://moviesmod.com.pl/#/schema/person/2a9ba79dc3c18188e96396ae471f06bf"
          },
          "description":"MoviesMod &#8211; MoviesFlix | TheMoviesverse | TheMoviesMod | TopMovies | ModList.in","breadcrumb":{
            "@id":"https://moviesmod.com.pl/#breadcrumb"
          },
          "inLanguage":"en-US"
        },
        {
          "@type":"BreadcrumbList",
          "@id":"https://moviesmod.com.pl/#breadcrumb",
          "itemListElement":
          [
            {
              "@type":"ListItem",
              "position":1,
              "name":"Home"
            }
          ]
        },
        {
          "@type":"WebSite",
          "@id":"https://moviesmod.com.pl/#website",
          "url":"https://moviesmod.com.pl/",
          "name":"Movies Mod | MoviesMod 2024, MoviesMod Original Site, MoviesMod Official","description":"MoviesMod &#8211; MoviesFlix | TheMoviesverse | TheMoviesMod | TopMovies | ModList.in","publisher":
          {
            "@id":"https://moviesmod.com.pl/#/schema/person/2a9ba79dc3c18188e96396ae471f06bf"
          },
          "alternateName":"MoviesMod | Movies Mod",
          "potentialAction":
          [
            {
              "@type":"SearchAction",
              "target":{
                "@type":"EntryPoint","urlTemplate":"https://moviesmod.com.pl/?s={search_term_string}"
              },
              "query-input":{
                "@type":"PropertyValueSpecification",
                "valueRequired":true,
                "valueName":"search_term_string"
              }
            }
          ],
          "inLanguage":"en-US"
        },
        {
          "@type":[
            "Person","Organization"
          ],
          "@id":"https://moviesmod.com.pl/#/schema/person/2a9ba79dc3c18188e96396ae471f06bf",
          "name":"admin",
          "image":{
            "@type":"ImageObject",
            "inLanguage":"en-US",
            "@id":"https://moviesmod.com.pl/#/schema/person/image/",
            "url":"https://moviesmod.com.pl/wp-content/uploads/moviesverse.webp",
            "contentUrl":"https://moviesmod.com.pl/wp-content/uploads/moviesverse.webp",
            "width":27,
            "height":27,
            "caption":"admin"
          },
          "logo":{
            "@id":"https://moviesmod.com.pl/#/schema/person/image/"
          },
          "sameAs":[
            "https://moviesmod.com.pl"
          ],
          "publishingPrinciples":"https://moviesmod.com.pl/announcements/",
          "ownershipFundingInfo":"https://moviesmod.com.pl/contact-us/",
          "actionableFeedbackPolicy":"https://moviesmod.com.pl/dmca/",
          "correctionsPolicy":"https://moviesmod.com.pl/request-us/",
          "ethicsPolicy":"https://moviesmod.com.pl/dmca/",
          "diversityPolicy":"https://moviesmod.com.pl/dmca/",
          "diversityStaffingReport":"https://moviesmod.com.pl/site-disclaimer/"
          "disclosurePolicy":"https://moviesmod.com.pl/dmca/",
          "address":{
            "@type":"PostalAddress",
            "streetAddress":"MoviesMod",
            "addressLocality":"MoviesMod",
            "addressRegion":"MoviesMod",
            "postalCode":"MoviesMod",
            "addressCountry":"MoviesMod"
          },
          "sameAs":[
            "https://moviesmod.com.pl"
          ],
          "url":"https://moviesmod.com.pl/",
          "description":"MoviesMod &#8211; MoviesFlix | TheMoviesverse | TheMoviesMod | TopMovies | ModList.in",
          "jobTitle":"MoviesMod",
          "telephone":"+91 1234567890",
          "email":"mailto:elitedevemon@gmail.com",
          "founder":"MoviesMod",
          "foundingDate":"2024-01-01",
          "foundingLocation":"MoviesMod",
          "sameAs":[
            "https://moviesmod.com.pl"
          ],
        }
      ],
      "@type":"WebPage",
      "@id":"https://moviesmod.com.pl/",
      "url":"https://moviesmod.com.pl/",
      "name":"MoviesMod &#8211; MoviesFlix | TheMoviesverse | TheMoviesMod | TopMovies | ModList.in",
      
    }
  </script>